### ISSUE TITLE
YSF.so: undefined symbol

### ISSUE THREAD

**Issue by Emialcaraz** [IllidanS4/YSF#101]
Failed (plugins/YSF.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEj)

I'm using centos 6.1, GCC version 4.7 and YSF_R20-RC4 

what can be the problem?

**Comment by IllidanS4** [comment]
Perhaps the server cannot find the correct libraries. Try building it with `make static`.
