### ISSUE TITLE
problem with the latest version of the YSF R20-RC4 plugin.

### ISSUE THREAD

**Issue by VladBlazevm** [IllidanS4/YSF#110]
There is no version of the plugin for Windows. Launched on Linux, the server crashed. It would be nice to do a make a Windows version. Waiting for an answer
Logs: [ERROR] signal 11 (SIGSEGV) catched; shutting log-core down (errno: 0, signal code: 1, exit status: 0)
[18:03:14] ===============================
[18:03:14] YSF - kurta999's version R20-RC4 loaded
[18:03:14] (c) 2008 Alex "Y_Less" Cole - (c) 2010 - 2016 kurta999
[18:03:14] Server version: 0.3.7 R2-1
[18:03:14] Operating System: Linux
[18:03:14] Built on: Dec 20 2018 at 16:56:24
[18:03:14] ===============================
[18:03:14]

**Comment by VladBlazevm** [comment]
> There is no version of the plugin for Windows. Launched on Linux, the server crashed. It would be nice to do a make a Windows version. Waiting for an answer
Logs: [ERROR] signal 11 (SIGSEGV) catched; shutting log-core down (errno: 0, signal code: 1, exit status: 0)

**Comment by n0bodysec** [comment]
Actually the releases has builds for Windows and Linux, also u can build it youself.
https://github.com/IllidanS4/YSF/releases

Are you running 0.3.7 R2-1 or R2-2-1?
Attach a debugger (like gdb) and you us the backtrace (bt command).

**Comment by VladBlazevm** [comment]
I use R-2. About 30 minutes after the launch the server crashes with this error: Logs: [ERROR] signal 11 (SIGSEGV) catched; shutting log-core down (errno: 0, signal code: 1, exit status: 0)

**Comment by n0bodysec** [comment]
Attach a debugger (like gdb) and you us the backtrace (bt command).

**Comment by IllidanS4** [comment]
Closed due to no further input.
