### ISSUE TITLE
Server won't respond to commands

### ISSUE THREAD

**Issue by tarikbrt2** [IllidanS4/YSF#113]
After I Installed latest version of YSF plugin and inc, my server stopped working. It won't respond to any commands. It feels like I lost connection to server. Anyone had same issue ?

Edit: There is no crashes or any logs.

**Comment by IllidanS4** [comment]
Try Ctrl+C with crashdetect and post the trace.

**Comment by tarikbrt2** [comment]
> Try Ctrl+C with crashdetect and post the trace.

It's working perfectly on Windows, but linux is problem, after I enter my login password it crashes.

**Comment by IllidanS4** [comment]
So does it crash or freeze? Which server version are you using?

**Comment by n0bodysec** [comment]
You can use `gdb` on Linux to get a debug log of the sa-mp server and its submodules.

**Comment by tarikbrt2** [comment]
Problem is I only bought game server not VPS :)

**Comment by n0bodysec** [comment]
Are u still facing this issue? @tarikbrt2

**Comment by IllidanS4** [comment]
Closed due to no further input.
