### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MaxAndolini** [IllidanS4/YSF#116]
I was getting errors when I tried to compile it myself. When I define them, the errors were fixed. By the way I am using the latest version of Visual Studio Enterprise.

![Screenshot_2](https://user-images.githubusercontent.com/6771759/85638148-d184b280-b68d-11ea-9257-22859a19fc01.png)

And defined this;

![Screenshot_1](https://user-images.githubusercontent.com/6771759/85638177-dfd2ce80-b68d-11ea-9c7d-14875d793127.png)

If there's anyone who gets the error, they can handle it that way.

**Comment by IllidanS4** [comment]
What errors?
