### ISSUE TITLE
GetWeaponSlot, GetPlayerSyncWeapon

### ISSUE THREAD

**Issue by ihnify** [IllidanS4/YSF#125]
getweaponslot returns the wrong slot, more than 13, and specifically if for example the player does not have a weapon, it will return 255, the same with GetPlayerSyncWeapon, returns a weapon greater than 47

**Comment by f0Re3t** [comment]
most likely, the bug is that the author of the plugin does not cast the type from BYTE to cell

**Comment by IllidanS4** [comment]
And why is this wrong? It returns the byte value of a particular field in the structure.

**Comment by IllidanS4** [comment]
The byte is now treated as signed, but it won't help you if you don't do sanity checks.
