### ISSUE TITLE
DeathProtection

### ISSUE THREAD

**Issue by NexiusTailer** [IllidanS4/YSF#129]
Death protection have its main code commented:
https://github.com/IllidanS4/YSF/blob/master/src/RPCs.cpp#L121-L128

It would be great to test it and make it work again.

UPD: I think the main problem was this piece of the check:
```
reasonid != WEAPON_ROCKETLAUNCHER && reasonid != WEAPON_HEATSEEKER
```
When there is no need to make that exclusion, but at the same time it needs to exclude "WEAPON_FLAMETHROWER"

So the final variant would be like that:
```
if (pKiller->syncData.byteWeapon != reasonid && pKiller->byteState != PLAYER_STATE_DRIVER)
{
	if (reasonid <= 46 && reasonid != WEAPON_FLAMETHROWER)
	{
		// logprintf("onplayerdeath error 1, synced weapon: %d, reason: %d", pKiller->syncData.byteWeapon, reasonid);
		return;
	}
}
```

UPD 2:
Also, we can make some reliable improvements according to old YSF versions:
```
if (pKiller->syncData.byteWeapon != reasonid && pKiller->byteState != PLAYER_STATE_DRIVER)
{
	if (reasonid == 49 || reasonid == 50 || reasonid <= 46 && reasonid != WEAPON_FLAMETHROWER)
	{
		// logprintf("onplayerdeath error 1, synced weapon: %d, reason: %d", pKiller->syncData.byteWeapon, reasonid);
		return;
	}
}
```

**Comment by IllidanS4** [comment]
`pPlayer->syncData.byteWeapon` is useless when the player is in a vehicle or a passenger. `pPlayer->vehicleSyncData.bytePlayerWeapon` and `pPlayer->passengerSyncData.bytePlayerWeapon` are to be used in that case.

Still there could be cases where it might prevent a legit kill, such as destroying someone's vehicle, causing it to explode, might report the weapon as the reasonid but the killer has enough time to hide it. Feel free to create a pull request from these changes, but some thorough testing will be needed.

**Comment by NexiusTailer** [comment]
> Still there could be cases where it might prevent a legit kill, such as destroying someone's vehicle, causing it to explode, might report the weapon as the reasonid but the killer has enough time to hide it. Feel free to create a pull request from these changes, but some thorough testing will be needed.

Seems I really missed that moment, thanks for note. But this can be changed to the condition which checks if a killer has this weapon at all (from the same source like GetPlayerWeaponData obtains from), not just armed now.

**Comment by NexiusTailer** [comment]
Another idea related to:
> `pPlayer->syncData.byteWeapon` is useless when the player is in a vehicle or a passenger. `pPlayer->vehicleSyncData.bytePlayerWeapon` and `pPlayer->passengerSyncData.bytePlayerWeapon` are to be used in that case.

If we don't have any problems with obtaining driver/passenger weapons anymore, we can do that check:
```
pKiller->byteState != PLAYER_STATE_DRIVER
```
only to validate if reasonid is sent as 49 and 50

The second check for weapons which player can hold may be applied for any sync type.
