### ISSUE TITLE
crash after reboot via server FCNPC

### ISSUE THREAD

**Issue by fergus-pwn** [IllidanS4/YSF#131]
Quote from ziggi: "The problem is in YSF, in SetPlayerObjectMaterial call"

[https://github.com/ziggi/FCNPC/issues/243](url)

**Comment by IllidanS4** [comment]
Is this the latest version of YSF?

**Comment by fergus-pwn** [comment]
Yes. YSF 2.1

**Comment by IllidanS4** [comment]
I thought that this error has been finally fixes. Well, try this in the config:
```
StorePlayerObjectsMaterial 0
```

**Comment by fergus-pwn** [comment]
Thanks
