### ISSUE TITLE
plugin crashed server

### ISSUE THREAD

**Issue by Dmitriy51** [IllidanS4/YSF#132]
native IsVehicleOccupied(vehicleid); this function

[debug] #0 f7b89f7f in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () in plugins/crashdetect.so
[debug] #1 f7b8281d in _ZN11CrashDetect20PrintNativeBacktraceERSoRKN2os7ContextE () in plugins/crashdetect.so
[debug] #2 f7b82e48 in _ZN11CrashDetect20PrintNativeBacktraceERKN2os7ContextE () in plugins/crashdetect.so
[debug] #3 f7b845dc in _ZN11CrashDetect7OnCrashERKN2os7ContextE () in plugins/crashdetect.so
[debug] #4 f7b8979f in ?? () in plugins/crashdetect.so
[debug] #5 f7f76bf0 in __kernel_rt_sigreturn () in linux-gate.so.1
[debug] #6 080d1480 in ?? () in sampsvr-port_5097
[debug] #7 f455f408 in _Z22HOOK_CVehicle__RespawnP8CVehicle () in plugins/YSF.so
[debug] #8 080950e4 in ?? () in sampsvr-port_5097
[debug] #9 f7b8246f in _ZN11CrashDetect15ProcessCallbackEiPiS0_ () in plugins/crashdetect.so
[debug] #10 f7b87feb in ?? () in plugins/crashdetect.so
[debug] Registers:
[debug] EAX: 0871df60 EBX: 00000001 ECX: c4f37864 EDX: 080d1480
[debug] ESI: 081ecc88 EDI: 00000001 EBP: fff56a68 ESP: fff56a2c
[debug] EIP: 080d1480 EFLAGS: 00010292
[debug] Stack:
[debug] ESP+00000000: f454b095 0871df60 00000001 081ecc88
[debug] ESP+00000020: f45bd000 fff56a98 f7f8b6e0 f454aec3
[debug] ESP+00000040: f455f408 081ecc88 0015bed4 fff56a88
[debug] ESP+00000060: 080d6bce 081ecc88 fff56b24 fff56ac8
[debug] ESP+00000080: 0015bef0 000b8f48 00000000 080d6ba0
[debug] ESP+000000a0: f7b8246f 08782268 00000007 fff56c6c
[debug] ESP+000000c0: f7f85dd6 fff56c10 00000000 00000000
[debug] ESP+000000e0: 081d4218 08782268 00000000 0015bef0
[debug] ESP+00000100: 0015bef0 000b8efc 00000056 f7f85dbf
[debug] ESP+00000120: f7f85dd6 fff56c70 00000000 fff56b98
[debug] ESP+00000140: 081d4218 00000000 081d421c 081d4220
[debug] ESP+00000160: f7f97d20 fff56c58 fff56b50 f7f85dbf
[debug] ESP+00000180: 00000000 00000000 fff56c30 fff56bf8
[debug] ESP+000001a0: f7f6337c f7f62e10 fff56c10 79732064
[debug] ESP+000001c0: f7bb2000 f7bb2890 f38ea008 0015bec8
[debug] ESP+000001e0: f3b4ab3c f7b87f87 f39a760c 08782268
[debug] ESP+00000200: f3b4ab3c 00157f00 0015bef0 f38ee6c8
[debug] ESP+00000220: 00000000 001005ac 000b8f48 f7bb2000
[debug] ESP+00000240: 00000000 00000000 00000003 689cc198
[debug] ESP+00000260: f7b840b4 08782268 00000000 00000003
[debug] ESP+00000280: f38ea008 f7f90e5f f4659196 f46881ec
[debug] ESP+000002a0: f7f97d20 000f4fa0 00000001 fff56cfc
[debug] ESP+000002c0: 00000000 00000003 00000000 00000001
[debug] ESP+000002e0: f7f66000 fff56e70 f7f97d20 fff56d38
[debug] ESP+00000300: f7b87e6f 0882ea00 00000000 00000003
[debug] ESP+00000320: f4789932 08782268 00000000 00000003
[debug] ESP+00000340: 081d4218 00000000 081d421c f38eb885
[debug] ESP+00000360: f46881ec 00000003 00000000 08782268
[debug] ESP+00000380: 00000000 fff56ed0 00000000 f7f85dbf
[debug] ESP+000003a0: f38eb885 00000000 081d421c f465b1a9
[debug] ESP+000003c0: f76c5e84 08782268 00000000 00000003
[debug] ESP+000003e0: f76c9249 08782268 00000000 00000003
[debug] Loaded modules:
[debug] 00000000 - 00188003 sampsvr-port_5097
[debug] f7f76000 - f7f76d82 linux-gate.so.1
[debug] f7f62000 - f7f6481b /lib/i386-linux-gnu/i686/cmov/libdl.so.2
[debug] f7f46000 - f7f60d2b /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
[debug] f7dc6000 - f7f4f5c0 /usr/libs/minimal/libstdc++.so.6
[debug] f7d80000 - f7dc4b43 /lib/i386-linux-gnu/i686/cmov/libm.so.6
[debug] f7d63000 - f7d7f3c4 /lib/i386-linux-gnu/libgcc_s.so.1
[debug] f7bb6000 - f7d6b22f /lib/i386-linux-gnu/i686/cmov/libc.so.6
[debug] f7f77000 - f7f97d6c /lib/ld-linux.so.2
[debug] f7b6a000 - f7bb23d4 plugins/crashdetect.so
[debug] f7a35000 - f7b6e7d8 plugins/raknet.so
[debug] f76a4000 - f7a39eb2 plugins/mysql.so
[debug] f7680000 - f76a3d32 /home/samp/clients/port_9678/port_9678/plugins/log-core.so
[debug] f766d000 - f767409f /lib/i386-linux-gnu/i686/cmov/librt.so.1
[debug] f665e000 - f66693ef /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
[debug] f634b000 - f650a0c0 plugins/pawncmd.so
[debug] f6644000 - f665b834 plugins/sscanf.so
[debug] f6305000 - f634a654 plugins/GeoIP.so
[debug] f475c000 - f4830b05 plugins/streamer.so
[debug] f662a000 - f6642dc8 plugins/GPS.so
[debug] f464e000 - f468abd4 plugins/fmt.so
[debug] f460d000 - f464dffe plugins/timerfix.so
[debug] f4524000 - f460ec83 plugins/YSF.so
[debug] f6623000 - f662797b /lib/i386-linux-gnu/i686/cmov/libnss_dns.so.2
[debug] f660b000 - f66232fb /lib/i386-linux-gnu/i686/cmov/libresolv.so.2

**Comment by IllidanS4** [comment]
Please add information like server version and frequency of the crash.

**Comment by n0bodysec** [comment]
Are you using SA-MP 0.3.7 R3?

**Comment by IllidanS4** [comment]
Closed due to no further information.
