### ISSUE TITLE
This plugin bugs car reflections or ENB mods

### ISSUE THREAD

**Issue by v1934** [IllidanS4/YSF#135]
Players have been reporting to me that car reflections (default SA ones) or ENB graphical mods are bugged only on my server. I couldn't find anything that could cause this for months. I commented out literally everything in my GM that had any effect on player's game, tried changing the way of creating vehicles etc until I found out its the YSF plugin causing this.

Setting `PassiveMode 1` automatically fixes the problem, but obviously lots of YSF functions stop working then. Even player colors are getting out of sync.

On stock game, sometimes (randomly) certain parts of cars have lighter color (especially doors & trunk on elegy).
With ENB, most of the time the cars have no ENB custom reflections on them, or only on some parts.
![Screenshot](https://user-images.githubusercontent.com/80751466/133855981-40a0c3ae-7bbd-4228-bacf-164df01da687.png)

See the screenshot, only some parts have the ENB reflection & they are lighter in color.
Before anyone says it's a bug of the game - it surely is, but it occurs ONLY when using YSF and I'm 100% sure about that.

I had no time to look into YSF deeply, but I might try fixing it since some of the stuff now stopped working after I enabled passive mode.
After a quick lookup I found this line in CPlugin.cpp:
```bsSync->Write((char*)&pNetGame->pVehiclePool, 212); // modelsUsed```

If I understand correctly it sends hard-coded 212 (so all models) as vehicle models used in the gamemode. It's just a guess, but it may be that the game bugs when it is told that every vehicle model is in use. I don't know what this value is used for in the game client, but I can guess it's some memory pre-allocation or something like this.

**Comment by IllidanS4** [comment]
Intriguing. Not sure if that line is related, but you did actually manage to find a bug there! It's supposed to send the first 212 bytes of CVehiclePool, but instead it sends the first 212 bytes of the CNetGame structure starting at the `pVehiclePool` pointer. Perhaps this could have been causing some strange crashes.

Could you try recompiling with the change, and if it still doesn't work, commenting the whole `case RPC_InitGame` branch and trying that?

**Comment by v1934** [comment]
I have compiled the plugin with your changes and after multiple tests, I can confirm that the issue is now fixed. Haven't observed any problem after multiple rejoins, vw changes and other. Earlier it was happening almost everytime.

Can you build a complete release with linux bins? Don't have any linux VM at the moment but if you cannot then I'll get one.

**Comment by IllidanS4** [comment]
Glad to hear! Thanks for pointing out the issue.

Of course, I'll release 2.2 soon anyway.

**Comment by IllidanS4** [comment]
@v1934 The Linux version is now available.
