### ISSUE TITLE
GetPlayer3DTextLabelVirtualW

### ISSUE THREAD

**Issue by netdnk** [IllidanS4/YSF#139]
Why there is this function? Can i put Player3DText in the virtual world? 
here is samp function:
CreatePlayer3DTextLabel(playerid, const text[], color, Float:X, Float:Y, Float:Z, Float:DrawDistance, attachedplayer=INVALID_PLAYER_ID, attachedvehicle=INVALID_VEHICLE_ID, testLOS=0)
help?

**Comment by IllidanS4** [comment]
I guess it is there because the Get3DTextLabel* functions were simply copied and changed to load the structure from another source. There is no real use to the function if you cannot set the virtual world in the first place.
