### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by antoinefra** [IllidanS4/YSF#4]
`hostname = "You are banned from this server.";`

Is it possible to make a bigger message than 51 characters? 

You are talking in your talking of the possibilities to edit the message :  gamemode, language. What are the default messages ? I personally don't see where there are ?

Thanks

**Comment by IllidanS4** [comment]
Hi! The limit appears to be enforced by SA-MP, it may be changeable, but no other server has that. `hostname` is "SA-MP Server", `gameMode` is "Unknown", and `language` is "-" by default, but these parameters already contain the variables set in your server when the callback is called.
