### ISSUE TITLE
Hiding and Showing player for other players

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [IllidanS4/YSF#41]
So I did try a code to hide player and then show it.

It worked fine the hiding part when it was called by a command what happened wrong was, when a player is show back by `ShowPlayerForPlayer(i,playerid);` that player sees our skin as CJ skin so it's not synced.
For this I had to set the players skin again.

Another was when I used these functions on Player Spawn.
```
if(HidePlayer[playerid])
	{
		for(new i=0; i<MAX_PLAYERS; i++)
		{
			if(pAdmin[i]) continue;
			HidePlayerForPlayer(i,playerid);
		}
	}
	else
	{
		for(new i=0; i<MAX_PLAYERS; i++)
		{
			ShowPlayerForPlayer(i,playerid);
		}
	}
```

This code won't work somehow.

**Comment by kurta999** [comment]
It's not really a "bug", however in the future I'll try to do something with it.

Hide/ShowPlayerForPlayer only sends RPC to client which purpose is only show or hide the given player to client.
