### ISSUE TITLE
SetVehicleSpawnInfo

### ISSUE THREAD

**Issue by ronixtey** [IllidanS4/YSF#54]
"respawntime" parameter doesn't work.

Whatever i write, vehicle disappears immediately when player gets out.
This starts happen after first respawn.

**Comment by kurta999** [comment]
Which version are you using? R18, R19 beta?

**Comment by Xerieos** [comment]
r18

**Comment by IllidanS4** [comment]
The parameter accepted values in milliseconds instead of in seconds like the other functions do. Fixed in a282170f841820983c4feb871b52a5f5156c58ef.
