### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by antoinefra** [IllidanS4/YSF#6]
Hello,

Could it be possible customization of client message such as : You are banned from this server, Invalid Name etc..

**Comment by IllidanS4** [comment]
I don't think it is possible. These messages are mostly stored in the game, not in the server. However, "SERVER: Bad admin password. Repeated attempts will get you banned." appears to be stored in the server executable, but I don't see necessity in allowing that to be changed.

**Comment by antoinefra** [comment]
Indeed, it was mostly to indicate an information to the player banned via RCON (example: Contact us ..)
