### ISSUE TITLE
|| instead of &&

### ISSUE THREAD

**Issue by NexiusTailer** [IllidanS4/YSF#69]
https://github.com/kurta999/YSF/blob/c26467c56ac44621dc26d66e2799b350d44efc3f/src/RPCs.cpp#L182

It seems that we should check for a mismatch on both weapon IDs, isn't it?
```
reasonid != WEAPON_ROCKETLAUNCHER && reasonid != WEAPON_HEATSEEKER
```

**Comment by NexiusTailer** [comment]
P.s. And why does this code exist at all? What false detections can it prevent?
```
&& (reasonid != WEAPON_ROCKETLAUNCHER || reasonid != WEAPON_HEATSEEKER) && pKiller->byteState != PLAYER_STATE_DRIVER
```

**Comment by kurta999** [comment]
This has been removed. Thanks.

**Comment by NexiusTailer** [comment]
It seems that this code is still exist without any changes.
