### ISSUE TITLE
CreateObject calls

### ISSUE THREAD

**Issue by JernejL** [IllidanS4/YSF#7]
Createobject() and destroyobject() are a superior way of making objects that do not break placing vehicles on top of them to any streamer, but that has a issue since it is visible in all virtual worlds. 

Ability to call the createobject rpc directly per player would be of much use, it would allow us to have streaming based only on virtual worlds - which would be a foolproof way of placing vehicles on top of objects in them.

**Comment by kurta999** [comment]
If I good understand, you wan't something like ShowCreateObjectForPlayer, HideCreateObjectForPlayer (of course, not with these names xD).

Anyway you can solve this problem with CreatePlayerObject & DestroyPlayerObject.

**Comment by JernejL** [comment]
well yes, but in that case, there goes quite some logic to do this for all players (managing join/parting, changing virtual worlds, permantntly storing lists of objs in pawn array structs).. being able to use the createobject rpc would be superior, it would not interfere / take slots from player-objects streamer, the only issue really is that i need constant objects without a streamer but only in one virtual world.

**Comment by NegativeIQ** [comment]
Actually streamer does not brake any vehicles (does not let the fall thru) if you use it correctly.

First your base objects needs to have streaming distance about 1.2-1.5 times the streaming distance of vehicles. Second, depending on your objects count in one place, you may use standard object stream (for every player), or if there are to many objects like on many stunt servers then create that object for each player, and streamer will handle that as CreatePlayerObject. Also creating base (ground) objects first and then everything else also helps.

**Comment by IllidanS4** [comment]
I agree with this, it would be extremely useful to me to be able to hide all created objects, because players on my server can create objects, and then show them all again.

**Comment by IllidanS4** [comment]
There is both `SendRPC` and `HideObjectForPlayer` now; closing.
