### ISSUE TITLE
0.3.DL Structs

### ISSUE THREAD

**Issue by ziggi** [IllidanS4/YSF#77]
### Discussion about 0.3.DL Structs

I was found some changes in `CPlayer` and `CPlayerPool` structs. Look at here: https://github.com/ziggi/FCNPC/commit/2871b1849610994e2c5be2a17fd299f7ee890ec8
But it's need more research.

**Comment by ziggi** [comment]
Another changes what I found: https://github.com/ziggi/FCNPC/commit/fb96ab6096e5f110cc0c91150466b89e409a692d

**Comment by IllidanS4** [comment]
Nice job! I made a branch for 0.3.DL, so you can make a pull request if you find out more. ;-)

**Comment by IllidanS4** [comment]
Linux addresses are ported, but untested. Please [test](https://github.com/IllidanS4/YSF/tree/0_3_DL) if you can.
