### ISSUE TITLE
RPC counters

### ISSUE THREAD

**Issue by JernejL** [IllidanS4/YSF#8]
If raknet has ability to have this internally - ability to get a counter of how many RPCs are waiting for ack by a client, for monitoring sync stability.

**Comment by kurta999** [comment]
Please explain me what is ack :D

**Comment by JernejL** [comment]
ACK - acknowledgments, meaning it's waiting for a RPC function it called to be confirmed with an ACK

**Comment by kurta999** [comment]
I've patched one 1 to 2 under GetPlayerNetStats. Result is awesome :O

I'll include this in R16. Hope it will help.

http://www.mfrserver.net/up/advanced_getnetworkstat.png

**Comment by kurta999** [comment]
http://forum.sa-mp.com/showpost.php?p=3663808&postcount=1287

Looks like I'm reopening this issue.
