### ISSUE TITLE
undefined symbol: _ZN8CAddress22FUNC_Logprintf_03DL_R1E)  

### ISSUE THREAD

**Issue by RazorGuigo** [IllidanS4/YSF#80]
after I compile ubuntu, with the libs in correct versions, and test the plugin:
`Loading plugin: YSF.so 
Failed (plugins/YSF.so: undefined symbol: _ZN8CAddress22FUNC_Logprintf_03DL_R1E)  `

**Comment by SteveDee98** [comment]
I have the same issue.
Did you fix it?
