### ISSUE TITLE
Support for 0.3.DL

### ISSUE THREAD

**Issue by SteveDee98** [IllidanS4/YSF#81]
Would be nice if there was a version for SAMP 0.3.DL

**Comment by IllidanS4** [comment]
The 0.3.DL branch should be working, the memory addresses and structures are already updated.

**Comment by SteveDee98** [comment]
Failed (plugins/YSF.so: undefined symbol: _ZN8CAddress22FUNC_Logprintf_03DL_R1E)

**Comment by SteveDee98** [comment]
Is there an static.so which i can use?

**Comment by IllidanS4** [comment]
I forgot to define logprintf address on Linux, apparently. Try compiling it now.
[YSF_static.zip](https://github.com/IllidanS4/YSF/files/1878268/YSF_static.zip)

**Comment by SteveDee98** [comment]
The static one works for me, big thanks 👍 :)
