### ISSUE TITLE
Samp 0.3 DL problem

### ISSUE THREAD

**Issue by DeveleruxMemphis** [IllidanS4/YSF#88]
I use SAMP 0.3 DL and YSF doesn't work.

I put plugins folder YSF.dll (0.3 DL banch version) and put server.cfg
Updated include and recompile. 

And I get this message:

"[21:15:19] 
[21:15:19] Server Plugins
[21:15:19] --------------
[21:15:19]  Loading plugin: YSF
[21:15:19] This version of YSF doesn't support SA-MP 0.3z
[21:15:19] Update to 0.3.7! http://sa-mp.com/download.php
[21:15:19] Error: Unknown Windows server version

[21:15:19] Error: Big part of YSF will be unusable for you"

And here includes: 
#include <a_samp>
#include <mapandreas>
#include <noclass>
#include <streamer>
#include <YSF>

and plugins:
plugins MapAndreas.dll streamer.dll pawncmd.dll sscanf.dll YSF.dll

Please fix. I develop server and I need to use YSF's functions.
Sorry bad english I am from Hungarian.

**Comment by IllidanS4** [comment]
There are no releases for 0.3.DL. Did you compile it yourself?

**Comment by DeveleruxMemphis** [comment]
Ohh no releases? I did these: I download R19 version and put server folder after I download 0.3 DL banch and put selver folder. Ohh I got it. Sorry I think 0.3 DL banch version is "released beta" version. Ohh bad english skills thanks.. So I really sorry and I have one more question.

**Comment by IllidanS4** [comment]
You can download the 0.3.DL branch and compile it yourself. It is in a mostly finished state actually, but it will not be released until the remaining issues are fixed, and I get the features I want there to work. Considering I am focused on other projects right now, that may take some time, but I do plan to revisit YSF in the future.

**Comment by Jewking** [comment]
So could u compile for us please? And wont release it. Just add here link as alpha rev.
It'll be really great man. 

Thx.

**Comment by DeveleruxMemphis** [comment]
Yeah. I same. I don't need release for 0.3 DL. But you can post alpha version? I want open server at Christmas and I need alpha or released version for 0.3DL. I don't need now but I need at December.

Thx.

**Comment by IllidanS4** [comment]
0.3.DL support is now included and tested.
