### ISSUE TITLE
Question & Suggestion

### ISSUE THREAD

**Issue by NemanjaMAX** [IllidanS4/YSF#95]
Hello IllidanS4, I have one question for you, my English is pretty bad so excuse me :)
I was playing on one Balcan server, i was trying to use Secondary Sync on OverLight Mod v3 which is almost undetectable by all anticheats, when i joined, my friend who told me about that cheat ( Yes, we have teamspeak which includes only grieffers, like team of 30 of us destroying servers we don't like ) started laughing after i throw few cars and he said "Only you see cars flying, others players do not see it ( which is right ). My question is: Is this server using YSF feature or Pawn.RakNet feature? I suppose they disable all incoming RPC's for player, but i do not see how they spot the iregullarity.
--- Now to the bright side ( Suggestion ):
I'm sure that you think this is not useful but it can actually be in team and other related stuff:
Its related to SetPlayerColor
I'm using this: 
AllowNickNameCharacter('#', true);
And I wan't only # to be coloured example BLUE on tablist except other chars ( "BLUE_COLOR"#"WHITE_COLOR"Wajttachu (name) )

**Comment by IllidanS4** [comment]
I don't know how the cheat works, so can't be sure how the protection is done. In fact, maybe it only uses the functions of SA-MP, not relying on YSF or Pawn.RakNet. I haven't really looked into this area in terms of using YSF.

As for the suggestion, this is achievable entirely in terms of Pawn. Allow `{` and `}` and use standard color codes in the nickname. Other than doing the same thing, how would YSF help in this?

**Comment by NemanjaMAX** [comment]
I don't see how is it possible to make something happens only on player's screen without RPC (You see cars and players flying but only you can see that ) 
Happy New Year my friend 23:57 :heart:
