### ISSUE TITLE
Player gangzones not working in RC20-4

### ISSUE THREAD

**Issue by FedeArre** [IllidanS4/YSF#97]
Player gangzones are not working in RC20-4 (DL), they just do not appear and CreatePlayerGangZone always returns 0.

Test code:
```
public OnPlayerConnect(playerid)
{
	new asd = CreatePlayerGangZone(playerid, 0, 0, 1000, 1000);
	PlayerGangZoneShow(playerid, asd, 0xF85B5BFF);
	return 1;
}
```

This code is working properly with R19

**Comment by n0bodysec** [comment]
@IllidanS4 I think you can close this too
