### ISSUE TITLE
Typo mistake: OnPlayerClientGameInit (lagcomp parameter)

### ISSUE THREAD

**Issue by NexiusTailer** [IllidanS4/YSF#99]
OnPlayerClientGameInit callback have &lacgompmode parameter with a little type mistake

https://github.com/IllidanS4/YSF/blob/32b35b8c891221bc39f90abe7ecfbb2ba312c561/sampsvr_files/pawno/include/YSF.inc#L440

😉

**Comment by IllidanS4** [comment]
Is it worth changing it even if it would break existing code?

**Comment by NexiusTailer** [comment]
I would change this but of course, notify about it in changelog.

**Comment by n0bodysec** [comment]
@IllidanS4 fixed in https://github.com/IllidanS4/YSF/commit/cbe33e90a10a839ef19366f2d1593d6c1accc0d6.

You forgot to update `YSF_examples.pwn` 😄
